version: "3.0"

services:
  postgres:
    container_name: postgres_social
    image: postgres:latest
    environment:
      - POSTGRES_DB=social
      - POSTGRES_USER=social_user
      - POSTGRES_PASSWORD=social_pass
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres_social:/var/lib/postgres_social/data
volumes:
  postgres_social: